#!/bin/sh

# Set these paths appropriately

BIN="/Users/kohei/Downloads/bin"
CMD="/Users/kohei/Downloads/cmd"
LIB="/Users/kohei/Downloads/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/catalan-abbreviations
PARFILE=${LIB}/catalan.par

$TOKENIZER -c -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
