#!/bin/sh

# Set these paths appropriately

BIN="/Users/kohei/Downloads/bin"
CMD="/Users/kohei/Downloads/cmd"
LIB="/Users/kohei/Downloads/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/greek-mwls.pl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/greek-abbreviations
PARFILE=${LIB}/greek.par

$TOKENIZER -a $ABBR_LIST $* |
$MWL |
# tagging
$TAGGER $OPTIONS $PARFILE

